# Utiliser l'image officielle Node.js
FROM node:14-alpine 

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les dépendances de package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code source de l'application
COPY . .

# Compiler l'application React
RUN npm run build

# Exposer le port 3000 pour accéder à l'application
EXPOSE 3000

# Commande pour démarrer l'application lorsque le conteneur est lancé
CMD ["npm", "start"]